=== mantou132/gem/packages/gem-book/schema.json
{
  "$ref": "#/definitions/CliConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "CliConfig": {
      "additionalProperties": false,
      "properties": {
        "base": {
          "type": "string"
        },
        "build": {
          "type": "boolean"
        },
        "config": {
          "type": "string"
        },
        "debug": {
          "type": "boolean"
        },
        "displayRank": {
          "type": "boolean"
        },
        "fallbackLanguage": {
          "anyOf": [
            {
              "$ref": "#/definitions/SupportLang"
            },
            {
              "const": "",
              "type": "string"
            }
          ]
        },
        "footer": {
          "type": "string"
        },
        "ga": {
          "type": "string"
        },
        "github": {
          "type": "string"
        },
        "global": {},
        "homeMode": {
          "type": "boolean"
        },
        "i18n": {
          "type": "boolean"
        },
        "icon": {
          "type": "string"
        },
        "ignored": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "json": {
          "type": "boolean"
        },
        "nav": {
          "items": {
            "$ref": "#/definitions/NavItem"
          },
          "type": "array"
        },
        "output": {
          "type": "string"
        },
        "plugin": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "port": {
          "type": "number"
        },
        "site": {
          "type": "string"
        },
        "sourceBranch": {
          "type": "string"
        },
        "sourceDir": {
          "type": "string"
        },
        "template": {
          "type": "string"
        },
        "theme": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Feature": {
      "additionalProperties": false,
      "properties": {
        "desc": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "desc"
      ],
      "type": "object"
    },
    "Hero": {
      "additionalProperties": false,
      "properties": {
        "actions": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "link": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            },
            "required": [
              "text",
              "link"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "desc": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "NavItem": {
      "additionalProperties": false,
      "properties": {
        "children": {
          "items": {
            "$ref": "#/definitions/NavItem"
          },
          "type": "array"
        },
        "features": {
          "items": {
            "$ref": "#/definitions/Feature"
          },
          "type": "array"
        },
        "groups": {
          "items": {
            "additionalProperties": false,
            "properties": {
              "members": {
                "items": {
                  "type": "string"
                },
                "type": "array"
              },
              "title": {
                "type": "string"
              }
            },
            "required": [
              "title",
              "members"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "hash": {
          "type": "string"
        },
        "hero": {
          "$ref": "#/definitions/Hero",
          "description": "below only homepage"
        },
        "isNav": {
          "type": "boolean"
        },
        "link": {
          "type": "string"
        },
        "navOrder": {
          "type": "number"
        },
        "navTitle": {
          "type": "string"
        },
        "redirect": {
          "type": "string"
        },
        "reverse": {
          "description": "below only dir",
          "type": "boolean"
        },
        "sidebarIgnore": {
          "type": "boolean"
        },
        "title": {
          "type": "string"
        },
        "type": {
          "enum": [
            "dir",
            "file",
            "heading"
          ],
          "type": "string"
        }
      },
      "required": [
        "link",
        "title"
      ],
      "type": "object"
    },
    "SupportLang": {
      "enum": [
        "zh",
        "en"
      ],
      "type": "string"
    }
  }
}

=== mantou132/gem/packages/gem/gem-book.cli.json
{
  "$schema": "../gem-book/schema.json",
  "title": "Gem",
  "icon": "../../logo.png",
  "i18n": true,
  "homeMode": true,
  "site": "https://gemjs.org",
  "sourceBranch": "docs",
  "nav": [
    {
      "title": "Lit-HTML",
      "link": "https://lit-html.polymer-project.org/guide"
    }
  ],
  "template": "docs/template.html",
  "plugin": ["raw", "docsearch", "sandpack", "code-group", "api"],
  "debug": true
}

=== mantou132/gem/packages/duoyun-ui/gem-book.cli.json
{
  "$schema": "../gem-book/schema.json",
  "template": "docs/template.html",
  "title": "DuoyunUI",
  "icon": "../../logo.png",
  "i18n": true,
  "fallbackLanguage": "zh",
  "sourceBranch": "docs",
  "plugin": ["media", "api", "sandpack", "raw", "docsearch?local", "example", "import"],
  "debug": true
}

=== mantou132/gem/packages/tap-ui/gem-book.cli.json
{
  "$schema": "../gem-book/schema.json",
  "template": "docs/template.html",
  "title": "TapUI",
  "icon": "../../logo.png",
  "i18n": true,
  "fallbackLanguage": "zh",
  "sourceBranch": "docs",
  "plugin": ["media", "api", "sandpack", "raw", "docsearch?local", "example", "import"],
  "debug": true
}
